"""Real Clash of Clans stats, generated by scripts/import_coc_data.py.

Do not edit by hand -- rerun the importer. Source: the npm package
`clash-of-clans-data`, which mirrors the Clash of Clans wiki.
Town hall level used: 13 (highest level unlocked at that TH).
"""

TOWN_HALL_LEVEL = 13

BUILDINGS = {
    'TOWN_HALL': {'hp': 10800.0, 'radius': 2.0, 'dps': 0.0, 'rng': 0.0, 'min_rng': 0.0, 'hits_air': False, 'hits_ground': True, 'splash': 0.0, 'level': 18, 'name': 'Town Hall'},
    'CANNON': {'hp': 2000.0, 'radius': 1.5, 'dps': 135.0, 'rng': 9.0, 'min_rng': 0.0, 'hits_air': False, 'hits_ground': True, 'splash': 0.0, 'level': 19, 'name': 'Cannon'},
    'ARCHER_TOWER': {'hp': 1600.0, 'radius': 1.5, 'dps': 120.0, 'rng': 10.0, 'min_rng': 0.0, 'hits_air': True, 'hits_ground': True, 'splash': 0.0, 'level': 19, 'name': 'Archer Tower'},
    'MORTAR': {'hp': 1700.0, 'radius': 1.5, 'dps': 42.0, 'rng': 11.0, 'min_rng': 0.0, 'hits_air': False, 'hits_ground': True, 'splash': 1.5, 'level': 13, 'name': 'Mortar'},
    'WIZARD_TOWER': {'hp': 2500.0, 'radius': 1.5, 'dps': 84.0, 'rng': 7.0, 'min_rng': 0.0, 'hits_air': True, 'hits_ground': True, 'splash': 1.5, 'level': 13, 'name': 'Wizard Tower'},
    'AIR_DEFENSE': {'hp': 1500.0, 'radius': 1.5, 'dps': 440.0, 'rng': 10.0, 'min_rng': 0.0, 'hits_air': True, 'hits_ground': False, 'splash': 0.0, 'level': 11, 'name': 'Air Defense'},
    'TESLA': {'hp': 1200.0, 'radius': 1.0, 'dps': 140.0, 'rng': 7.0, 'min_rng': 0.0, 'hits_air': True, 'hits_ground': True, 'splash': 0.0, 'level': 12, 'name': 'Hidden Tesla'},
    'INFERNO': {'hp': 3300.0, 'radius': 1.0, 'dps': 1800.0, 'rng': 9.0, 'min_rng': 0.0, 'hits_air': True, 'hits_ground': True, 'splash': 0.0, 'level': 7, 'name': 'Inferno Tower'},
    'XBOW': {'hp': 4000.0, 'radius': 2.0, 'dps': 155.0, 'rng': 14.0, 'min_rng': 0.0, 'hits_air': True, 'hits_ground': True, 'splash': 0.0, 'level': 8, 'name': 'X-Bow'},
    'STORAGE': {'hp': 3300.0, 'radius': 1.5, 'dps': 0.0, 'rng': 0.0, 'min_rng': 0.0, 'hits_air': False, 'hits_ground': True, 'splash': 0.0, 'level': 14, 'name': 'Gold Storage'},
    'RESOURCE_BUILDING': {'hp': 1280.0, 'radius': 1.5, 'dps': 0.0, 'rng': 0.0, 'min_rng': 0.0, 'hits_air': False, 'hits_ground': True, 'splash': 0.0, 'level': 15, 'name': 'Gold Mine'},
    'WALL': {'hp': 9000.0, 'radius': 0.5, 'dps': 0.0, 'rng': 0.0, 'min_rng': 0.0, 'hits_air': False, 'hits_ground': True, 'splash': 0.0, 'level': 14, 'name': 'Wall'},
}

UNITS = {
    'TANK': {'hp': 8200.0, 'dps': 80.0, 'speed': 1.0, 'rng': 1.0, 'is_air': False, 'splash': 0.0, 'housing': 30, 'level': 10, 'name': 'Golem'},
    'DPS': {'hp': 230.0, 'dps': 38.0, 'speed': 1.5, 'rng': 0.4, 'is_air': False, 'splash': 0.0, 'housing': 1, 'level': 9, 'name': 'Barbarian'},
    'WALL_BREAKER': {'hp': 112.0, 'dps': 86.0, 'speed': 2.0, 'rng': 1.0, 'is_air': False, 'splash': 1.5, 'housing': 2, 'level': 9, 'name': 'Wall Breaker'},
    'RANGED': {'hp': 56.0, 'dps': 31.0, 'speed': 2.0, 'rng': 3.5, 'is_air': False, 'splash': 0.0, 'housing': 1, 'level': 9, 'name': 'Archer'},
    'AIR': {'hp': 4200.0, 'dps': 330.0, 'speed': 1.3333333333333333, 'rng': 3.0, 'is_air': True, 'splash': 1.5, 'housing': 20, 'level': 8, 'name': 'Dragon'},
    'SPLASH': {'hp': 250.0, 'dps': 245.0, 'speed': 1.3333333333333333, 'rng': 3.0, 'is_air': False, 'splash': 1.5, 'housing': 4, 'level': 10, 'name': 'Wizard'},
}
